#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## Openbox Pipemenu to open applications as root

# Variables and functions
MENUS_LIBDIR='/usr/share/archcraft/openbox/menulib'
if ! . "$MENUS_LIBDIR/archcraft.cfg" 2> /dev/null; then
	echo "Error: Failed to locate archcraft.cfg in $MENUS_LIBDIR" >&2
	exit 1
fi

# cmd
root_cmd="$HOME/.config/openbox-themes/scripts/asroot"

# menu
menuStart
	menuItem 'Terminal ( konsole)' "$root_cmd ' konsole'"
	menuItem 'File Manager (nemo)' "$root_cmd 'dbus-run-session nemo'"
	menuItem 'Text Editor (code)' "$root_cmd 'code'"
	menuSeparator
	menuItem 'File Manager CLI (ranger)' "$root_cmd ' konsole -e ranger'"
	menuItem 'Text Editor CLI (vim)' "$root_cmd ' konsole -e vim'"
	menuSeparator
	menuItem 'QT5 Settings' "$root_cmd 'qt5ct'"
	menuItem 'kvantum Manager' "$root_cmd 'kvantummanager'"
menuEnd
