#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## Kill if already running
killall -9 xfsettingsd picom polybar mpd dunst ksuperkey xfce4-power-manager

## Restore Wallpaper
nitrogen --restore

## xfce4-settings daemon
xfsettingsd &

## polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

## Enable power management
xfce4-power-manager &

## Start Compositing Manager
exec picom &

## Launch Polybar
bash ~/.config/openbox-themes/themes/polybar.sh

## Notification Daemon
exec dunst &

## Start Music Player Daemon
exec mpd &

## Launch Plank
exec plank &

## Thunar Daemon
exec thunar --daemon &

## Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

## Open Terminals
terminator -x cava &
terminator -x ncmpcpp &
terminator -x pipes.sh -p 99 -t 6 -r 0 &
terminator -x neofetch --off | less -rc~ &

## Open Apps
armcord &
firefox &
steam &
